# _config.yml - GitHub Pages configuration
title: VerseVista
description: Transform your images into beautiful poetry with AI
author: Masumi Yano
url: https://masumiyano.github.io/VerseVista

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO and social media
twitter:
  username: luke_y
  card: summary_large_image

social:
  name: Masumi Yano
  links:
    - https://github.com/MasumiYano

# Exclude files from processing
exclude:
  - versevista.py
  - main.py
  - requirements.txt
  - .env
  - __pycache__/
  - .idea/
  - .devcontainer/
